/* Auto-generated by genmsg_cpp for file /home/rainer/ros/playground/msg/Encoder.msg */
#ifndef PLAYGROUND_MESSAGE_ENCODER_H
#define PLAYGROUND_MESSAGE_ENCODER_H
#include <string>
#include <vector>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/message.h"
#include "ros/time.h"


namespace playground
{
template <class ContainerAllocator>
struct Encoder_ : public ros::Message
{
  typedef Encoder_<ContainerAllocator> Type;

  Encoder_()
  : x(0)
  , y(0)
  {
  }

  Encoder_(const ContainerAllocator& _alloc)
  : x(0)
  , y(0)
  {
  }

  typedef int16_t _x_type;
  int16_t x;

  typedef int16_t _y_type;
  int16_t y;


private:
  static const char* __s_getDataType_() { return "playground/Encoder"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROSCPP_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "6d78a6b8c9650c754bf0432d3d1707c3"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROSCPP_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "int16 x\n\
int16 y\n\
\n\
"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROSCPP_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROSCPP_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, x);
    ros::serialization::serialize(stream, y);
    return stream.getData();
  }

  ROSCPP_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, x);
    ros::serialization::deserialize(stream, y);
    return stream.getData();
  }

  ROSCPP_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(x);
    size += ros::serialization::serializationLength(y);
    return size;
  }

  typedef boost::shared_ptr< ::playground::Encoder_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::playground::Encoder_<ContainerAllocator>  const> ConstPtr;
}; // struct Encoder
typedef  ::playground::Encoder_<std::allocator<void> > Encoder;

typedef boost::shared_ptr< ::playground::Encoder> EncoderPtr;
typedef boost::shared_ptr< ::playground::Encoder const> EncoderConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::playground::Encoder_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::playground::Encoder_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace playground

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::playground::Encoder_<ContainerAllocator> > {
  static const char* value() 
  {
    return "6d78a6b8c9650c754bf0432d3d1707c3";
  }

  static const char* value(const  ::playground::Encoder_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x6d78a6b8c9650c75ULL;
  static const uint64_t static_value2 = 0x4bf0432d3d1707c3ULL;
};

template<class ContainerAllocator>
struct DataType< ::playground::Encoder_<ContainerAllocator> > {
  static const char* value() 
  {
    return "playground/Encoder";
  }

  static const char* value(const  ::playground::Encoder_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::playground::Encoder_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int16 x\n\
int16 y\n\
\n\
";
  }

  static const char* value(const  ::playground::Encoder_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::playground::Encoder_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::playground::Encoder_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.x);
    stream.next(m.y);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Encoder_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::playground::Encoder_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::playground::Encoder_<ContainerAllocator> & v) 
  {
    s << indent << "x: ";
    Printer<int16_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<int16_t>::stream(s, indent + "  ", v.y);
  }
};


} // namespace message_operations
} // namespace ros

#endif // PLAYGROUND_MESSAGE_ENCODER_H

